
AllCops:
    NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'bin/bundle'
Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Max: 120
  Exclude:
    - 'bin/bundle'